/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rz.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={500}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.medal}
        position={[1.02, 0.23, 0.78]}
        scale={[1.38, 1.08, 1.41]}
      />
      <mesh
        geometry={nodes.Curve010.geometry}
        material={materials.SVGMat}
        position={[2.2, 0.23, 1.58]}
        rotation={[3.11, 1.29, -3.11]}
        scale={[30.04, 0.89, 30.04]}
      />
    </group>
  )
}

useGLTF.preload('/rz.gltf')
